frontend/controllers/ArticleController.php
<?php

namespace frontend\controllers;

use frontend\models\VKModel;
use Yii;
use frontend\models\Article;
use frontend\models\ArticleSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\VarDumper;
//echo '<pre>';
//var_dump(Yii::$app->request->post());
//echo '</pre>';
//die();


/**
 * ArticleController implements the CRUD actions for Article model.
 */
class ArticleController extends Controller
{
    public function behaviors()
    {
        return [

            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'create', 'update', 'status', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'create', 'update', 'delete'],
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['status'],
                        'roles' => ['moder'],
                    ],
                ],
            ],

            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Article models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    /**
     * Lists all Article models.
     * @return mixed
     */
    public function actionStatus()
    {
        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->searchStatus(Yii::$app->request->queryParams);

        return $this->render('status', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Article model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Article model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Article(['scenario' => Article::SCENARIO_CREATE]);
        $model->status = Article::ARTICLE_PROCESSING_STATUS;
        $model->user_id = Yii::$app->user->id;

        if ($model->load(Yii::$app->request->post()))
        {
            if (Yii::$app->request->isPost)
            {
                $file = UploadedFile::getInstance($model, 'image');

                $model->image = $model->upload($file,Yii::$app->user->id, $model->image);

                $model->save();

            }
            Yii::$app->session->setFlash('article', 'Статья будет доступна для публикации после обработки модератором');
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return string|\yii\web\Response
     * @throws HttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->status == Article::ARTICLE_ALLOW_STATUS && !Yii::$app->user->can('moder')) {
            throw new HttpException(403 ,'Материал уже опубликован. Для измениения обратитесь к администратору сайта\группы');
        }

        $currentImage = $model->image;
        if ($model->load(Yii::$app->request->post()))
        {
            if (Yii::$app->request->isPost)
            {

                $file = UploadedFile::getInstance($model, 'image');

                if ($file) {
                    $model->image = $model->upload($file,Yii::$app->user->id, $currentImage);
                }

            }
            $model->image = $currentImage;
            $model->save();

            Yii::$app->session->setFlash('article', 'Статья будет доступна для публикации после обработки модератором');
            return $this->redirect(['view', 'id' => $model->id]);
        }


        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return \yii\web\Response
     * @throws HttpException
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        if ($model->status == Article::ARTICLE_ALLOW_STATUS && !Yii::$app->user->can('moder')) {
            throw new HttpException(403 ,'Материал уже опубликован. Для удаления обратитесь к администратору сайта\группы');
        }

        unlink(Yii::getAlias('@frontend') . '/web/uploads/users/' . '' . $model->image);
        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Article model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Article the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Article::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionNewPublications()
    {
        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->searchNew(Yii::$app->request->queryParams);

        return $this->render('new-publications', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionTheBestPublications()
    {
        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->searchBest(Yii::$app->request->queryParams);

        return $this->render('the-best-publications', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionWinnersLastWeeks()
    {
        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->searchPosition(Yii::$app->request->queryParams);

        return $this->render('winners-last-weeks', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,

        ]);
    }

    public function actionUpdatePoint() {
        //получить все articles с датой публикации - меньше месяца назад
        //SELECT * FROM TABLE WHERE tc_date >= DATE_SUB(CURRENT_DATE, INTERVAL 30 DAY)

        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->searchRepost(Yii::$app->request->queryParams);

        $articles = $dataProvider->getModels();
        $vk = new VKModel();


        foreach ($articles as $article) {
            $article->point = $vk->getRepostCount($article->id);
            $article->save();
            sleep(1);
        }

        die();

        return $this->render('update-point', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,

        ]);

    }
}

frontend/controllers/UserController.php
<?php
namespace frontend\controllers;

use frontend\models\Article;
use frontend\models\VKModel;
use Yii;
use common\models\User;
use common\models\UserSearch;
use frontend\models\ImageUpload;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            //Доступ только для админа
            [
                'class' => AccessControl::className(),
                'only' => ['index', 'create'],
                'rules' => [
                    [
                        'actions' => ['index', 'create'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],

            ],

            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


    public function actionIndex()
    {
        $searchModel = new UserSearch();
        //queryParams - В запросе GET значения параметров.
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     * @throws \Exception
     */
    public function actionCreate()
    {
        if(Yii::$app->user->can('admin')) {

            $model = new User();

            $model->generateAuthKey();

            if ($model->load(Yii::$app->request->post()) && $model->save())
            {
                $auth = Yii::$app->authManager;
                $role = $auth->getRole('user');
                $auth->assign($role, $model->id);

                return $this->redirect(['view', 'id' => $model->id]);
            }

            return $this->render('create', [
                'model' => $model,
            ]);
        }

        return $this->redirect(['site/index']);
    }

    /**Обновляет существующую модель пользователя.
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model !== null) {
            $currentImage = $model->photo;
            if ($model->load(Yii::$app->request->post())) {
                if (Yii::$app->request->isPost) {
                    // получаем экземпляр загруженного файла
                    $file = UploadedFile::getInstance($model, 'photo');
                    $model->photo = $model->uploadFile($file, $currentImage);

                    $model->save();
                }
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }


    /*Удаляет существующую модель пользователя - Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    /**
     * @param $id
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionDelete($id)
    {
        $user = $this->findModel($id);
        if($user) {
            $user->first_name = 'DELETE';
            $user->last_name = 'DELETE';

            $user->save(false);
            $this->actionLogout();
        }
        return $this->redirect(['index']);
    }


    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }


    /**
     * @param $uid
     * @param $first_name
     * @param $last_name
     * @param $photo
     * @param $hash
     * @return string|\yii\web\Response
     * @throws \Exception
     */
    public function actionLoginVk()
    {
        //VarDumper::dump(Yii::$app->request->get('first_name'));die;
        $sign = '';

        foreach (Yii::$app->request->get() as $key => $param) {

            if ($key == 'hash' || $key == 'sign') {
                continue;
            }

            $sign .=$param;
        }

        $secret = \Yii::$app->params['secretKeyApp'];

        if(hash_hmac('sha256', $sign, $secret) == Yii::$app->request->get('sign'))
        {
            $vk = new VKModel();
            $vkUserData = $vk->getUserData(Yii::$app->request->get('viewer_id'));

            $user = User::findOne(Yii::$app->request->get('viewer_id'));

            if(!$user) {
                $user = new User();
                $user->id = $vkUserData['id'];
                $user->generateAuthKey();

                if ($user->save(false))
                {
                    $auth = Yii::$app->authManager;
                    $role = $auth->getRole('user');
                    $auth->assign($role, $user->id);
                }
            }

            $user->first_name = $vkUserData['first_name'];
            $user->last_name = $vkUserData['last_name'];
            $user->photo = $vkUserData['photo_50'];

            $user->save();
            Yii::$app->user->login($user);

            if(Yii::$app->request->get('hash') === Article::ACTION_CREATE_HASH) {
                return $this->redirect(['article/create']);
            } else {
                return $this->redirect(['site/index']);
            }

        } else {
            throw new HttpException(401 ,'Ошибка авторизации');
        }

    }

    public function actionLoginVkSite($uid, $first_name, $last_name, $photo, $hash)
    {
        $secret = \Yii::$app->params['secretKeyAppSite'];
        $app = \Yii::$app->params['appSite'];

        $user_hash = md5($app.$uid.$secret);
        if($user_hash !== $hash) {
            throw new HttpException(401 ,'Ошибка авторизации');
        }

        $user = $this->updateUserFromVK($uid);
        Yii::$app->user->login($user);

        return $this->redirect(['article/create']);
    }

    protected function updateUserFromVK($userId)
    {
        $vk = new VKModel();
        $vkUserData = $vk->getUserData($userId);
        $user = User::findOne($userId);

        if(!$user) {
            $user = new User();
            $user->id = $vkUserData['id'];
            $user->generateAuthKey();

            if ($user->save(false))
            {
                $auth = Yii::$app->authManager;
                $role = $auth->getRole('user');
                $auth->assign($role, $user->id);
            }
        }

        $user->first_name = $vkUserData['first_name'];
        $user->last_name = $vkUserData['last_name'];
        $user->photo = $vkUserData['photo_50'];

        $user->save();

        return $user;
    }

    /**
     * @param $id
     * @return User|null
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']],
        ['label' => 'About', 'url' => ['/site/about']],
        ['label' => 'Article', 'url' => ['/article/index']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->first_name . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/new_layout.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;
use yii\widgets\Menu;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <!--    обеспечение правильной визуализации и сенсорного масштабирования-->
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php $this->registerCsrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body>
    <?php $this->beginBody() ?>

    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Навигация</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                <a href="<?= Url::toRoute(['/site/index'])?>" class="navbar-brand text-uppercase">kotofotka</a>
            </div>

            <?php if (!Yii::$app->user->isGuest):?>
                <ul class="nav navbar-nav navbar-right collapse navbar-collapse">
                    <?php if(Yii::$app->user->can('admin')):?>
                        <li><a href="<?= Url::toRoute(['/user/index'])?>">Просмотр всех пользователей</a></li>
                    <?php endif;?>
                    <?php if(Yii::$app->user->can('moder')):?>
                        <li><a href="<?= Url::toRoute(['/article/status'])?>">Обработка статей</a></li>
                    <?php endif;?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Публикации <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?= Url::toRoute(['/article/new-publications'])?>">Новые публикации</a></li>
                            <li><a href="<?= Url::toRoute(['/article/the-best-publications'])?>">Лучшие публикации</a></li>
                            <li class="divider"></li>
                            <li><a href="<?= Url::toRoute(['/article/winners-last-weeks'])?>">Победители прошлых недель</a></li>
                        </ul>
                    </li>
                    <li><a href="<?= Url::toRoute(['/article?id='.Yii::$app->user->id])?>">Мои публикации</a></li>
                    <li><a href="<?= Url::toRoute(['/user/update?id='.Yii::$app->user->id])?>">Мой профиль</a></li>
                    <li><a href="<?= Url::toRoute(['/user/logout'])?>">Выход (<?=Yii::$app->user->identity->first_name?>)</a></li>
                </ul>
            <?php else: ?>
                <ul class="nav navbar-nav navbar-right collapse navbar-collapse">
                            <li><a href="<?= Url::toRoute(['/article/new-publications'])?>">Новые публикации</a></li>
                            <li><a href="<?= Url::toRoute(['/article/the-best-publications'])?>">Лучшие публикации</a></li>
                            <li class="divider"></li>
                            <li><a href="<?= Url::toRoute(['/article/winners-last-weeks'])?>">Победители прошлых недель</a></li>
                </ul>
            <?php endif;?>
        </div>
    </div>

    <!--            body { background: url(/images/138.jpg) 0 0 repeat; }-->

    <div class="container main_container">
        <?= $content ?>
    </div>


    <footer class="footer">
        <div class="container-fluid">
            <p class="pull-left">&copy; Все права защищены <?= date('Y') ?></p>
        </div>
    </footer>

    <?php $this->endBody() ?>

    </body>
    </html>
<?php $this->endPage() ?>