backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/ArticleController.php
<?php

namespace frontend\controllers;

use frontend\models\VKModel;
use Yii;
use frontend\models\Article;
use frontend\models\ArticleSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\VarDumper;
//echo '<pre>';
//var_dump(Yii::$app->request->post());
//echo '</pre>';
//die();


/**
 * ArticleController implements the CRUD actions for Article model.
 */
class ArticleController extends Controller
{
    public function behaviors()
    {
        return [

            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'create', 'update', 'status', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'create', 'update', 'delete'],
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['status'],
                        'roles' => ['moder'],
                    ],
                ],
            ],

            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Article models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    /**
     * Lists all Article models.
     * @return mixed
     */
    public function actionStatus()
    {
        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->searchStatus(Yii::$app->request->queryParams);

        return $this->render('status', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Article model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Article model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Article(['scenario' => Article::SCENARIO_CREATE]);
        $model->status = Article::ARTICLE_PROCESSING_STATUS;
        $model->user_id = Yii::$app->user->id;

        if ($model->load(Yii::$app->request->post()))
        {
            if (Yii::$app->request->isPost)
            {
                $file = UploadedFile::getInstance($model, 'image');

                $model->image = $model->upload($file,Yii::$app->user->id, $model->image);

                $model->save();

            }
            Yii::$app->session->setFlash('article', 'Статья будет доступна для публикации после обработки модератором');
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return string|\yii\web\Response
     * @throws HttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->status == Article::ARTICLE_ALLOW_STATUS && !Yii::$app->user->can('moder')) {
            throw new HttpException(403 ,'Материал уже опубликован. Для измениения обратитесь к администратору сайта\группы');
        }

        $currentImage = $model->image;
        if ($model->load(Yii::$app->request->post()))
        {
            if (Yii::$app->request->isPost)
            {

                $file = UploadedFile::getInstance($model, 'image');

                if ($file) {
                    $model->image = $model->upload($file,Yii::$app->user->id, $currentImage);
                }

            }
            $model->image = $currentImage;
            $model->save();

            Yii::$app->session->setFlash('article', 'Статья будет доступна для публикации после обработки модератором');
            return $this->redirect(['view', 'id' => $model->id]);
        }


        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return \yii\web\Response
     * @throws HttpException
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        if ($model->status == Article::ARTICLE_ALLOW_STATUS && !Yii::$app->user->can('moder')) {
            throw new HttpException(403 ,'Материал уже опубликован. Для удаления обратитесь к администратору сайта\группы');
        }

        unlink(Yii::getAlias('@frontend') . '/web/uploads/users/' . '' . $model->image);
        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Article model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Article the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Article::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionNewPublications()
    {
        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->searchNew(Yii::$app->request->queryParams);

        return $this->render('new-publications', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionTheBestPublications()
    {
        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->searchBest(Yii::$app->request->queryParams);

        return $this->render('the-best-publications', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionWinnersLastWeeks()
    {
        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->searchPosition(Yii::$app->request->queryParams);

        return $this->render('winners-last-weeks', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,

        ]);
    }

    public function actionUpdatePoint() {
        //получить все articles с датой публикации - меньше месяца назад
        //SELECT * FROM TABLE WHERE tc_date >= DATE_SUB(CURRENT_DATE, INTERVAL 30 DAY)

        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->searchRepost(Yii::$app->request->queryParams);

        $articles = $dataProvider->getModels();
        $vk = new VKModel();


        foreach ($articles as $article) {
            $article->point = $vk->getRepostCount($article->id);
            $article->save();
            sleep(1);
        }

        die();

        return $this->render('update-point', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,

        ]);

    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use frontend\models\ArticleSearch;
use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\helpers\VarDumper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\web\ErrorAction;
use yii\captcha\CaptchaAction;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'rules', 'logout', 'signup', 'login'],
                'rules' => [
                    [
                        'actions' => ['index', 'rules', 'signup', 'login'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['index', 'rules', 'logout', 'signup', 'login'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => ErrorAction::class,
            ],
            'captcha' => [
                'class' => CaptchaAction::class,
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


    public function actionIndex()
    {
        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->searchNew(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,

        ]);
    }


    public function actionRules()
    {
        return $this->render('rules');
    }


    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';

        return $this->render('login', [
            'model' => $model,
        ]);
    }


    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }


    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            Yii::$app->session->setFlash('success', 'Thank you for registration. Please check your inbox for verification email.');
            return $this->goHome();
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            }

            Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Verify email address
     *
     * @param string $token
     * @throws BadRequestHttpException
     * @return yii\web\Response
     */
    public function actionVerifyEmail($token)
    {
        try {
            $model = new VerifyEmailForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($user = $model->verifyEmail()) {
            if (Yii::$app->user->login($user)) {
                Yii::$app->session->setFlash('success', 'Your email has been confirmed!');
                return $this->goHome();
            }
        }

        Yii::$app->session->setFlash('error', 'Sorry, we are unable to verify your account with provided token.');
        return $this->goHome();
    }

    /**
     * Resend verification email
     *
     * @return mixed
     */
    public function actionResendVerificationEmail()
    {
        $model = new ResendVerificationEmailForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            }
            Yii::$app->session->setFlash('error', 'Sorry, we are unable to resend verification email for the provided email address.');
        }

        return $this->render('resendVerificationEmail', [
            'model' => $model
        ]);
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        }

        return $this->render('contact', [
            'model' => $model,
        ]);
    }
}

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<script type="text/javascript" src="https://vk.com/js/api/share.js?95" charset="windows-1251"></script>
<?php
use yii\data\Pagination;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\LinkPager;

$this->title = 'Конкурс фотографий домашних питомцев. Денежные призы!';
$user = Yii::$app->user->identity;
$appSite = \Yii::$app->params['appSite'];
?>

<div class="row marketing info_block">

    <div class="col-lg-10" >
        <div class="row">
            <div class="col-lg-7" >
                <h1 class="text-left">Конкурс фотографий с денежными призами</h1>
                <p class="text-left lead" >Каждую неделю подводится итог голосования, в котором именно Ты решишь, чей питомец станет победителем.<br></p>
                <div class="info_money">
                    <p class="text-center">Будь в тройке лидеров и получай призы:</p>
                    <dl class="dl-horizontal">
                        <dt>1 место &#128571;</dt>
                        <dd>1000 рублей</dd>
                        <dt>2 место &#128568;</dt>
                        <dd>500 рублей</dd>
                        <dt>3 место &#128573;</dt>
                        <dd>200 рублей</dd>
                    </dl>
                </div>
            </div>

            <div class="col-lg-5" >
                <img class="img-responsive" src="<?= Url::toRoute(['/uploads/kotic_ava2.png'])?>" alt="avatar_kotofotka">
            </div>
        </div>

        <blockquote class="blockquote-reverse">
            <p class="text-right">Чей четвероногий друг, по-твоему мнению, достоин первого места?<br>
                А, может, именно <strong>твой</strong> покорит сердца других любителей на этой неделе.
                <br>
                Хочешь это проверить?&#128521
                <br>
                Не забудь ознакомиться с <a href="<?= Url::toRoute(['rules'])?>">правилами конкурса</a>.
            </p>
        </blockquote>
    </div>

    <div class="col-lg-2 info_text">
        <?php if(!Yii::$app->user->isGuest):?>
            <p><a class="btn btn-primary" href="<?= Url::toRoute(['/article/create'])?>">Участвовать<br>в конкурсе</a></p>
        <?php else:?>
<!--            <a class="btn btn-primary" href="https://vk.com/app--><?//= \Yii::$app->params['appID'] . '#' . \frontend\models\Article::ACTION_CREATE_HASH ?><!--">Участвовать<br>в конкурсе</a>-->
            <button class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Участвовать<br>в конкурсе</button>

            <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title">Авторизуйтесь и создайте свой первый пост</h4>
                        </div>

                        <script type="text/javascript" src="https://vk.com/js/api/openapi.js?160"></script>
                        <script type="text/javascript">
                            VK.init({apiId: <?= $appSite?>});
                        </script>

                        <!-- VK Widget -->
                        <br>
                        <div id="vk_auth" class="center-block"></div>
                        <br>
                        <script type="text/javascript">
                            VK.Widgets.Auth("vk_auth", {"authUrl":"/user/login-vk-site"});
                        </script>
                    </div>
                </div>
            </div>


        <?php endif;?>
    </div>

</div>

<?php $model = $dataProvider->getModels(); ?>
<div class="row text-center article-list">

    <?php foreach ($model as $articleNum => $article):?>
        <div class="col-md-6">
            <?= $this->render('@frontend/views/article/_article', [
                'article' => $article,
            ]) ?>
        </div>
        <?= ($articleNum + 1) % 2 == 0 ? '<div class="clearfix"></div>' : '' ?>
    <?php endforeach;?>

</div>
<?= yii\grid\GridView::widget([
    'dataProvider' => $dataProvider,
    'layout' => '{pager}',
])?>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<!--<div class="site-login">-->
<!--    <h1>--><?//= Html::encode($this->title) ?><!--</h1>-->
<!---->
<!--    <p>Please fill out the following fields to login:</p>-->
<!---->
<!--    <div class="row">-->
<!--        <div class="col-lg-5">-->
<!--            --><?php //$form = ActiveForm::begin(['id' => 'login-form']); ?>
<!---->
<!--                --><?//= $form->field($model, 'first_name')->textInput(['autofocus' => true]) ?>
<!---->
<!--                --><?//= $form->field($model, 'last_name')->textInput() ?>
<!---->
<!--                --><?//= $form->field($model, 'password')->passwordInput() ?>
<!---->
<!--                --><?//= $form->field($model, 'rememberMe')->checkbox() ?>
<!---->
<!--                <div style="color:#999;margin:1em 0">-->
<!--                    If you forgot your password you can --><?//= Html::a('reset it', ['site/request-password-reset']) ?><!--.-->
<!--                    <br>-->
<!--                    Need new verification email? --><?//= Html::a('Resend', ['site/resend-verification-email']) ?>
<!--                </div>-->
<!---->
<!--                <div class="form-group">-->
<!--                    --><?//= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
<!--                </div>-->
<!---->
<!--            --><?php //ActiveForm::end(); ?>
<!--            -->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<div class="login">
    <div>
        <script type="text/javascript" src="https://vk.com/js/api/openapi.js?162"></script>
        <script type="text/javascript">
            VK.init({apiId: 7130762});
        </script>

        <!-- VK Widget -->
        <div id="vk_auth"></div>
        <script type="text/javascript">
            VK.Widgets.Auth("vk_auth", {"authUrl":"/user/login-vk"});
        </script>
    </div>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resendVerificationEmail.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Resend verification email';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-resend-verification-email">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A verification email will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'resend-verification-email-form']); ?>

            <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

            <div class="form-group">
                <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/rules.php
<?php
$this->title = 'Правила еженедельного конкурса';

use yii\helpers\Html;
use yii\helpers\Url;
$user = Yii::$app->user->identity;

?>
<div class="rules">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="main-text">
        <h3>Еженедельный конкурс - призовой фонд 1700 рублей</h3>
        <p>
            Конкурс является еженедельным и проводится с 00:00 понедельника до 23:59 субботы.<br>
            Призовой фонд каждого еженедельного конкурса составляет 1700 рублей, которые распределяются среди победителей следующим образом:
        </p>
        <dl class="dl-horizontal">
            <dt>1 место&#128571;</dt>
            <dd>1000 рублей</dd>
            <dt>2 место&#128568;</dt>
            <dd>500 рублей</dd>
            <dt>3 место&#128573;</dt>
            <dd>200 рублей</dd>
        </dl>

        <p>
            Полученый от вас пост (изображение, текст) обрабатывается модератором и проходит проверку на плагиат и цензуру.
            <br>Результаты конкурса будут отображаться каждое воскресенье до 23:59 (по московскому времени).
        </p>

    </div>

    <div class="rules-text">
        <br>
        <h4>Условия участия:</h4>
        <ul>
            <li>Каждый Участник конкурса должен пройти авторизацию через социальную сеть Вконтакте</li>
            <li>Каждый авторизированный Пользователь может создавать неограниченное количество публикаций для участия в Конкурсе</li>
            <li>Для участия в каждом еженедельном конкурсе, Участник должен указать <a href="<?= Url::toRoute(['user/update?id=' . $user->id])?>">способ получения Денежного Вознаграждения</a> (по умолчанию метод оплаты - деньги ВК)</li>
            <li>Выявленная "накрутка" репостов (привлечение множества неактивных аккаунтов, аккаунтов не существующих пользователей) - повлечёт за собой исключение из конкурса всех активных публикаций и блокировку Участника</li>
            <li>Загруженная фотография поста Участника проходит проверку на плагиат</li>
            <li>Написанный текст поста Участником проходит проверку на плагиат и орфографию</li>
            <li>Пользователь даёт согласие на любое использование, редактирование и публикацию своих материалов от имени организаторов конкурса</li>
            <li>Организаторы Конкурса вправе отказать в публикации любых материалов Участника, без объяснения причин</li>
            <li>Организаторы Конкурса вправе в любой момент завершить Конкурс или изменить данные Правила без предварительного оповещения</li>
            <li>Организаторы Конкурса не несут ответственности за любые затраты или упущеную выгоду Участника, связанные с проведением Конкурса</li>
        </ul>

        <br>
        <h4>При соблюдении всех условий ваш пост будет одобрен и опубликуется на сайте и группе Вконтакте.</h4>

        <br>
        <h4>Как выявляются победитель и призовые места?</h4>
        <p>При определении призёров, ключевое значение имеет количество репостов публикации Участника в группе Конкурса ВК, однако организаторы вправе определять призёров на своё усмотрение в каждом конкретном случае.</p>

        <h3>Каждому Участнику желаем удачи)))</h3>
    </div>
    